# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislator', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('ad', models.IntegerField(db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('for_search', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legislator_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=32)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='legislator.LegislatorDetail')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='proposer',
            field=models.ManyToManyField(through='bill.Legislator_Bill', to='legislator.LegislatorDetail'),
        ),
        migrations.AlterUniqueTogether(
            name='legislator_bill',
            unique_together=set([('legislator', 'bill')]),
        ),
    ]
