# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 07:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('ad', models.IntegerField(db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
            ],
        ),
    ]
