# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 13:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20151203_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billmotions',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billmotions',
            name='sitting',
        ),
        migrations.RemoveField(
            model_name='ttsmotions',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='api_bill_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='last_action',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='last_action_at',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='proposed_by',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sitting_introduced',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='summary',
        ),
        migrations.AddField(
            model_name='bill',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='for_search',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legislator_bill',
            name='role',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='legislator_bill',
            name='petition',
        ),
        migrations.RemoveField(
            model_name='legislator_bill',
            name='priproposer',
        ),
        migrations.AlterUniqueTogether(
            name='legislator_bill',
            unique_together=set([('legislator', 'bill')]),
        ),
        migrations.DeleteModel(
            name='BillMotions',
        ),
        migrations.DeleteModel(
            name='ttsMotions',
        ),
    ]
