# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-06 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_law'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='bill.Bill'),
        ),
    ]
