# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sittings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('former_names', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegislatorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.IntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('party', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('elected_party', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('caucus', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.IntegerField(blank=True, db_index=True, null=True)),
                ('county', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('in_office', models.BooleanField(db_index=True)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('bill_param', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('vote_param', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('attendance_param', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='each_terms', to='legislator.Legislator')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='legislator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislator.LegislatorDetail'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sittings.Sittings'),
        ),
        migrations.AlterUniqueTogether(
            name='legislatordetail',
            unique_together=set([('legislator', 'ad')]),
        ),
    ]
