# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 07:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='identifiers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
