# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 09:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislator', '0002_legislatordetail_elected_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislatordetail',
            name='attendance_param',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='legislatordetail',
            name='bill_param',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='legislatordetail',
            name='contacts',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='legislatordetail',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='legislatordetail',
            name='term_end',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='legislatordetail',
            name='vote_param',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
