# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-22 10:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislator', '0003_auto_20160330_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
