# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 06:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislator', '0003_auto_20151203_0905'),
    ]

    operations = [
        migrations.RunSQL("update legislator_legislatordetail set party = json_build_array(json_build_object('name', party,'start_at', term_start,'end_at', term_end->>'date'))"),
        migrations.AlterField(
            model_name='legislatordetail',
            name='party',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
