# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislator', '0001_initial'),
        ('sittings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.IntegerField(blank=True, db_index=True, null=True)),
                ('conflict', models.NullBooleanField(db_index=True)),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislator.LegislatorDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('vote_seq', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('conflict', models.NullBooleanField()),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sittings.Sittings')),
                ('voter', models.ManyToManyField(through='vote.Legislator_Vote', to='legislator.LegislatorDetail')),
            ],
        ),
        migrations.AddField(
            model_name='legislator_vote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Vote'),
        ),
        migrations.AlterUniqueTogether(
            name='legislator_vote',
            unique_together=set([('legislator', 'vote')]),
        ),
    ]
