# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-21 14:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidates_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='identifiers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
