# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 09:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_terms_councilor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='contact_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='councilor',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='politicalcontributions',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
