# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20151203_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='cec_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
