# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sittings',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('committee', models.TextField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('ad', models.PositiveIntegerField()),
                ('session', models.PositiveIntegerField()),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
