# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legislator_Committees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.IntegerField()),
                ('session', models.IntegerField()),
                ('chair', models.BooleanField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Committees', to_field=b'name')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislator.LegislatorDetail')),
            ],
        ),
        migrations.AddField(
            model_name='committees',
            name='members',
            field=models.ManyToManyField(through='committees.Legislator_Committees', to='legislator.LegislatorDetail'),
        ),
    ]
