# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32)),
                ('pro', models.IntegerField(default=0)),
                ('vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standpoints', to='vote.Vote')),
            ],
        ),
        migrations.CreateModel(
            name='User_Standpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standpoint.Standpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standpoints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user_standpoint',
            unique_together=set([('standpoint', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='standpoint',
            unique_together=set([('title', 'vote')]),
        ),
    ]
