# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-06 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standpoint',
            name='uid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standpoint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_standpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_standpoint',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user_standpoint',
            unique_together=set([('user', 'standpoint')]),
        ),
        migrations.AlterIndexTogether(
            name='user_standpoint',
            index_together=set([('user', 'standpoint')]),
        ),
        migrations.RunSQL("UPDATE standpoint_standpoint SET uid = 'vote-' || vote_id || '-' || title;")
    ]
