# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-06 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_add_bill_and_unique_uid'),
        ('standpoint', '0002_add_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='standpoint',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standpoints', to='bill.Bill'),
        ),
        migrations.AlterField(
            model_name='standpoint',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='standpoint',
            unique_together=set([]),
        ),
    ]
